### ISSUE TITLE
Bug in Updating Info in User

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#108]
When you update information on the users, once you click save, no notifications will appear prompting the admin that changes has been made. When refresh, that information will then updated.

**Comment by orvzjhp** [comment]
Same with admin account, everytime mo update kos profile kay no notification, then if imo i refresh ma reflect ang changs

**Comment by chuakarlo** [comment]
ok na ang admin account.. ang super admin kay ok na sad pero wala pa gimerge ni FSKREUZ.. :)
