### ISSUE TITLE
Delete Badge on Admin

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#111]
When I try to delete pending badges, it pops up a message that the badge has been deleted but still visible on the map. If you refresh it, still visible on the map.

**Comment by orvzjhp** [comment]
edit. I can delete pending badges but there are other badges like "Jagna Lol", "yeyeye", "Masskes", "Cebu Plant Sanctuary"

**Comment by orvzjhp** [comment]
but there are other badges like "Jagna Lol", "yeyeye", "Masskes", "Cebu Plant Sanctuary" cannot be deleted

**Comment by fskreuz** [comment]
Cannot replicate. Works fine on the deployed app.
