### ISSUE TITLE
BUG Statistics

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#125]
Statistics won't load after you add a new badge.

**Comment by MarianneBorces** [comment]
- Sayup ang data sa mga trees.
- Please Add a check box that when clicked/checked, all the trees check boxed will be checked or if unchecked kay ma uncheck all trees check box

**Comment by chichiJPN** [comment]
Fixed wrong data and added check box when clicked.

**Comment by MarianneBorces** [comment]
wait. verifying on whether pending badges should be included in the statistics or not.

**Comment by MarianneBorces** [comment]
This is still a bug since ang municipality kay ang name of place

**Comment by chichiJPN** [comment]
Please check when amil updates web

**Comment by MarianneBorces** [comment]
ang municipalities iyang i-display sa drop down kay ang kato ra gihapon na add sa badges???

**Comment by MarianneBorces** [comment]
@chichiJPN yea chi, all municipalities should be complete.
