### ISSUE TITLE
Log in requirement

### ISSUE THREAD

**Issue by jambryx** [fskreuz/Tree-Trail#135]
log in problems with usernames having less than 6 characters
![image](https://cloud.githubusercontent.com/assets/9988462/6669650/fee4842e-cc34-11e4-9129-9e98f08e8c9c.png)
becomes
![image](https://cloud.githubusercontent.com/assets/9988462/6669663/1146d590-cc35-11e4-88bf-fbf0895ca406.png)

**Comment by MarianneBorces** [comment]
resolved.
