### ISSUE TITLE
Update Notification Modal on Admin

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#140]
Every an admin updates information from their profile, for example if I want to update my contact number, it pops up a modal stating that the Name has been successfully updated, not the contact number.

**Comment by MarianneBorces** [comment]
using superadmin account:
Step 1: click manage users
step 2: update user information
A pop-up note will appear but it will only stay for 3 seconds. 
Expected output: the user has to click dismiss button before it disappears.

**Comment by MarianneBorces** [comment]
okay. close this
