### ISSUE TITLE
Badge Approval > Reject Badge

### ISSUE THREAD

**Issue by jambryx** [fskreuz/Tree-Trail#144]
Reject badge directly deletes a badge.
Create confirm reject badge before deleting.
![image](https://cloud.githubusercontent.com/assets/9988462/6672390/2b653676-cc47-11e4-9ba2-10150de684c1.png)

**Comment by fskreuz** [comment]
fixed: https://github.com/fskreuz/Tree-Trail/commit/1f679c17c504a2130200a625664dd9c8cbf9a148
