### ISSUE TITLE
Badge Approval

### ISSUE THREAD

**Issue by jambryx** [fskreuz/Tree-Trail#145]
remove trash can (delete badge function) from Badge Approval
![image](https://cloud.githubusercontent.com/assets/9988462/6672443/8b09ba16-cc47-11e4-8a28-363e97d235d4.png)

**Comment by fskreuz** [comment]
fixed: https://github.com/fskreuz/Tree-Trail/commit/3d07634df521af31a7bea8c65d67e867e8a25163

**Comment by MarianneBorces** [comment]
this is okay. close this
