### ISSUE TITLE
Resize Picture in badges (if naa)

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#151]
Resize picture in badges to a minimum size like 200 x 150. Keep aspect ratio. Basta placeholder for resized picture is 200 x 150 ang size.

**Comment by fskreuz** [comment]
fixed: https://github.com/fskreuz/Tree-Trail/commit/5fe62dab0395078a66408ee105e3d395201e0810

**Comment by MarianneBorces** [comment]
the photos are corrupted -_-

**Comment by fskreuz** [comment]
Wiped old photos and db entries from db (probably old buggy code or upload while deploy going on). Please test again.

**Comment by MarianneBorces** [comment]
okay. close this
