### ISSUE TITLE
Add Badge

### ISSUE THREAD

**Issue by jambryx** [fskreuz/Tree-Trail#152]
pre: superadmin account
Steps:
1. clicked on map
2. added a badge
result = badge is "UNAPPROVED"

![image](https://cloud.githubusercontent.com/assets/9988462/6673498/9e8b7528-cc4e-11e4-8d27-dd6ca45c0487.png)

-------------------------------------------------
it should be that, the badge is already approved because it is an administrative account created the badge..

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/0e1443db29a108a4eafe65d49b3c7083cb2a4dce

**Comment by MarianneBorces** [comment]
Using super admin account:
If you add a badge and leave the municipality as is (default:Danao)
inig tan-aw nimo sa information: walay naka save sa municipality

**Comment by MarianneBorces** [comment]
it becomes unapproved again

**Comment by MarianneBorces** [comment]
it asks permission to approve the badge even if your using superadmin account

**Comment by MarianneBorces** [comment]
yeah okay. close this
