### ISSUE TITLE
Add Close functionality to sidebar

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#153]
As a guest user, when I click an approved badge and a sidebar appears, I should be able to have an option to close the sidebar para dili samok ig navigate sa map.

**Comment by fskreuz** [comment]
Cancel does the same thing.

**Comment by fskreuz** [comment]
fixed: https://github.com/fskreuz/Tree-Trail/commit/9869f2f125e1ef6169dda9d7b468097f0c825cd2

**Comment by MarianneBorces** [comment]
okay na ni. close this
