### ISSUE TITLE
Rejecting Pending Badge (Admin and Superadmin)

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#161]
As admin or superadmin, I should be able to delete any pending badges.

1. The admin or superadmin goes to view pending badge option on the drop down menu.
2. The admin or superadmin selects any pending badges.
3. The admin or superadmin rejects that selected badge.
4. The system notifies the admin or superadmin, if yes that badge would be deleted, if no it wont.
4. After choosing yes, that badge would still remain in the map.

**Comment by fskreuz** [comment]
Works fine. Internet may be slow on yours (map requests updated badges from server after delete).
