### ISSUE TITLE
Updating Pending Badges turns it to Approved Badge

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#163]
1. Admin / Superadmin clicks any pending badge.
2. Admin / Superadmin edits that chosen pending badge.
3. Upon saving, the status of the pending badge will change to an approved badge, the badge icon will turn from Gray to any color (red,yellow or green) according to its abundance.

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/690f0d5d43efcb683a1b22f55bdf3b4b8b286ece
