### ISSUE TITLE
Rejecting Badge Bug

### ISSUE THREAD

**Issue by MarianneBorces** [fskreuz/Tree-Trail#171]
using superadmin/admin account:
step 1: click unapproved badge
step 2: click reject
2 pop-ups will appear.
1. are you sure you want to reject location?
after clicking ok
2. location has been deleted 
and a check box on whether to prevent the page from adding dialogs

after checking the box, and clicked ok. 
Rejecting badge would not function anymore

**Comment by fskreuz** [comment]
This is a security feature of the browser to prevent dialogs. This is beyond the reach of our code. The solution for this is to reopen the page in another tab.
