### ISSUE TITLE
Pending Badge's Photo Error

### ISSUE THREAD

**Issue by mitziel** [fskreuz/Tree-Trail#178]
If an ADMIN edits the information of a pending badge, (like e.g, changing the severity from scarce to abundant), the photo uploaded by the guest won't appear anymore after saving the changes. where did the photo of the tree go?

**Comment by fskreuz** [comment]
fixed: https://github.com/fskreuz/Tree-Trail/commit/992625ddc589f76bd15384272aef104ec0a7fb60
