### ISSUE TITLE
View Pending Badges Bug

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#179]
Pre: Login as admin
1. Go to Contacts page
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

Pre: Login as admin
1. Go to About Page
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

Pre: Login as admin
1. Go to About Page
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

Pre: Login as admin
1. Go to View Feedbacks
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

Pre: Login as admin
1. Go to Manage Announcements
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

Pre: Login as admin
1. Go to Contact Page
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

Pre: Login as admin
1. Go to Announcements Page
2. Click dropdown sa Welcome <user>
3. When View Pending Badges clicked, not redirecting to map and showing pending badges.

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/56deec3f1f77372cf68733cac31779a13fc27af4

**Comment by CugalM** [comment]
uki na.:)
