### ISSUE TITLE
Allow Filters

### ISSUE THREAD

**Issue by chuakarlo** [fskreuz/Tree-Trail#18]
As a user, I should be able to filter my search as to the municipality, severity, plant type

**Comment by MarianneBorces** [comment]
cannot be checked kay walay makit-an na badges

**Comment by fskreuz** [comment]
Then you add badges, approve them and see if they get filtered.

**Comment by MarianneBorces** [comment]
yes, the problem is dle ma accept ang badges. sent a video in facebook

**Comment by jeanathegreat** [comment]
Filter badge bug - Tried to Filter badges but in filtering badges, even unapproved badges are included in the filter.

Steps to replicate bug:
1. Login as admin
2. There should be unapproved badges for the three types
3. Click Filter Badges link on Navbar
4. Click checkbox for Abundant, Scarce or Average
Result:
Unapproved badges with types equal to the checkboxes are also shown after filtering.
E.g. Unapproved scarce badge is seen when badges are filtered to show scarce badgs only.
Unapproved abundant badge is seen when badges are filtered to show abundant badge.
Unapproved average badge is seen when badges are filtered to show average badge.

What should be:
Unapproved badges should not be included when badges are filtered according to Severity.

**Comment by fskreuz** [comment]
https://github.com/fskreuz/Tree-Trail/commit/a70a9b4791698a563bfbdedf1c6f860941d387fe

**Comment by MarianneBorces** [comment]
if i will check all (abundant, average and scarce), all badges can be seen.
if i will uncheck all (abundant, average and scarce), all badges can be seen.
