### ISSUE TITLE
Header Inconsistency

### ISSUE THREAD

**Issue by mitziel** [fskreuz/Tree-Trail#196]
Please observe its order(what comes 1st, next, and so on), font size&style&color, background color, 

A. User side header links:
1. Tree Trail
2. About Project Tree Tail
3. Filter Badges
4. Contact
5. Announcements
6. Feedback
7. Login (please decide the final button color, font color&type&size, bg color)

B. Super Admin links:
1. Tree Trail
2. Statistics
3. About Project Tree Tail
4. Filter Badges
5. Contact
6. Announcements
7. Welcome, TEXT_HERE (bantayi ang contents sa drop down, must be consistent in all Super Admin Pages)
        - Edit Profile
	- Manage User Accounts
	- Manage Contacts
	- Manage Announcements
	- View Pending Badges
	- View Feedbacks
	- Logout

C. Admin Modules
1. Tree Trail
2. Statistics
3. About Project Tree Tail
4. Filter Badges
5. Contact
6. Announcements
7. Welcome, TEXT_HERE (bantayi ang contents sa drop down, must be consistent in all Admin Pages)
        - Edit Profile
	- Manage Contacts
	- Manage Announcements
	- View Pending Badges
	- View Feedbacks
	- Logout

**Comment by mitziel** [comment]
And also pls rename "View Feedback" to "Manage Feedback" in SuperAdmin/Admin drop down

**Comment by not-jay** [comment]
A is complete

**Comment by not-jay** [comment]
B is complete

**Comment by not-jay** [comment]
C is complete

**Comment by not-jay** [comment]
C is complete

**Comment by not-jay** [comment]
Screenshots just incase
Before:
![before](https://cloud.githubusercontent.com/assets/900439/10195467/5658d03a-67c0-11e5-82af-f056691ed33d.PNG)
After: (About Page)
![after-about](https://cloud.githubusercontent.com/assets/900439/10195468/565dd166-67c0-11e5-980f-444d35322672.PNG)
After: (Main Page)
![after-map](https://cloud.githubusercontent.com/assets/900439/10195469/565f9622-67c0-11e5-9ff8-2af7bed56ae9.PNG)
