### ISSUE TITLE
[back-end] Create wiki for project

### ISSUE THREAD

**Issue by fskreuz** [fskreuz/Tree-Trail#2]
# Acceptance Criteria

- [x] Have page for entities and their properties
- [x] Have page for endpoints and returns for each entity
    - [x] Must adhere to RESTful web API design
    - [x] Must return in JSON format
- [ ] Have page for database structures

**Comment by MarianneBorces** [comment]
NOT FOUND.

**Comment by not-jay** [comment]
@MarianneBorces I believe it's [this](https://github.com/fskreuz/Tree-Trail/wiki). (spoiler alert, it's probably outdated by now)

**Comment by fskreuz** [comment]
This was supposed to be for documentation during development. Closing coz outdated.
