### ISSUE TITLE
Tree Trail Home & About

### ISSUE THREAD

**Issue by jambryx** [fskreuz/Tree-Trail#209]
add the bug of having the same name for the home page and about page in the Bugs/Concerns Sheet of https://docs.google.com/spreadsheets/d/1WIfo6ZvhplwsywUNh190go0sAhAWVpH8NkFbe7kQsRU/edit#gid=240863237

**Comment by not-jay** [comment]
Commit not-jay/Tree-Trail@7d79bae should fix this
