### ISSUE TITLE
Create Contacts Page

### ISSUE THREAD

**Issue by chuakarlo** [fskreuz/Tree-Trail#21]
As a user, I should be able to view a list of contact person with connections about tree planting and other involved parties

**Comment by arpelayo** [comment]
asa ko mokuha sa mga details ani?

**Comment by arpelayo** [comment]
manual ang pag input ani? or naa sa database ang mga contact persons and etc nia e load lang sa page?

**Comment by arpelayo** [comment]
@jeanathegreat  @chuakarlo @f

**Comment by MarianneBorces** [comment]
NOT FOUND. on the online site. please pull request

**Comment by arpelayo** [comment]
naka pull request na
