### ISSUE TITLE
Missing drop down contents

### ISSUE THREAD

**Issue by jambryx** [fskreuz/Tree-Trail#215]
Go to this link : https://docs.google.com/spreadsheets/d/1WIfo6ZvhplwsywUNh190go0sAhAWVpH8NkFbe7kQsRU/edit#gid=240863237

Sheet Name: Bugs/Concerns
Bug # 3

Please close if resolved na ni in #181

**Comment by not-jay** [comment]
Commit not-jay/Tree-Trail@21c6089 should fix this
