### ISSUE TITLE
Approve pending requests(Admin)

### ISSUE THREAD

**Issue by chuakarlo** [fskreuz/Tree-Trail#23]
As Admin, I should be able to approve or deny any requests from guests in the Map module.

**Comment by MarianneBorces** [comment]
Can reject but not Accept. kindly add pop up message to make sure if i-reject ba jud niya

**Comment by fskreuz** [comment]
https://github.com/fskreuz/Tree-Trail/commit/54e3898e7f0fe21fd9e38844a1a8e40c600287d9

**Comment by jeanathegreat** [comment]
There is currently a bug in theapprove pending badges

The badges are colored gray (unapproved), but when clicking each unapproved badge, there is no Accept/Reject option.

**Comment by fskreuz** [comment]
Checking.

**Comment by fskreuz** [comment]
![image](https://cloud.githubusercontent.com/assets/1582932/6655307/603a0336-cb34-11e4-8b63-c01be74735ea.png)

Works on the live app.
