### ISSUE TITLE
Add pictures in Badge

### ISSUE THREAD

**Issue by chuakarlo** [fskreuz/Tree-Trail#27]
As a user, I should be able to upload photos about the place being pinned.

**Comment by jeanathegreat** [comment]
Pictures not added. Kindly fix this. Thanks

**Comment by MarianneBorces** [comment]
Bug- a photo should be seen or a notification should be seen if uploading is done.

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/826ec540afa55d8f3bc5d515d4bf20e39efe3f2b

**Comment by MarianneBorces** [comment]
okay!
