### ISSUE TITLE
[back-end] Create database structures

### ISSUE THREAD

**Issue by fskreuz** [fskreuz/Tree-Trail#3]
# Acceptance criteria

- [x] Must adhere to entity specifications as stated in the wiki: https://github.com/fskreuz/Tree-Trail/wiki
- [ ] Changes must be exported via sql dump (bzip compression preferred) and included in the repo
- [x] Must be in MySQL
- [ ] Add import and export procedures in the wiki

**Comment by MarianneBorces** [comment]
ok...
