### ISSUE TITLE
[front-end] Create a map component

### ISSUE THREAD

**Issue by fskreuz** [fskreuz/Tree-Trail#5]
# Acceptance Criteria

- [x] Display a map using any map provider (preferrably Google Maps)
- [x] Must be able to display markers using data from API. See wiki for details on data sources.
- [x] Clicking on markers should display sidebar containing the name of the location
- [x] Map must be centered on Cebu province on page load

**Comment by fskreuz** [comment]
See: http://app-treetrail.rhcloud.com/

**Comment by fskreuz** [comment]
https://github.com/fskreuz/Tree-Trail/commit/ea6e6028d934ce41941cd5882ff712f5a304fd07

**Comment by MarianneBorces** [comment]
ok
