### ISSUE TITLE
UX Improvement for CRUD Badge

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#51]
Kindly include an indicator that user has successfully added a badge, or that the newly added badge is now pending for approval.

Also kindly make the Close button for the sidebar more visible.

**Comment by jeanathegreat** [comment]
Edit:
Kindly include an indicator that user has successfully added a badge, or that the newly added badge is now pending for approval, after "Save" button is clicked.

**Comment by fskreuz** [comment]
Pending approval cannot be implemented because there's no facility to do authentication (read: Login, Auth etc.). Please address these issues first with the other teams.
