### ISSUE TITLE
UX Improvement for Add Badge

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#52]
When Add Badge mode is clicked or if user is in Add Badge mode, Add Badge link should be highlighted and mouse cursor should change to indicate that the user can now add badge anywhere on the map.

On the side window that will show when a location on the map is clicked, a "Cancel" button should also be present. When clicked, side bar slides out of view.

**Comment by fskreuz** [comment]
- "Add Badge" mode redundant. User can just click on the map and the form shows up. The form is self-explanatory.

**Comment by fskreuz** [comment]
https://github.com/fskreuz/Tree-Trail/commit/53a94d3bec5eed65ea9307f78b01efbdd5db9710
