### ISSUE TITLE
Add Badge Functionality - Upload Photos button

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#55]
Upload Photos button is not working as it should be aka no functionality. Kindly fix this. Thanks!

**Comment by jeanathegreat** [comment]
Upload photos button still not working. Moving this card to Bugs.

**Comment by jeanathegreat** [comment]
I tried to upload a photo and it said "Uploading. Please Wait" but photo was not actually uploaded.

**Comment by fskreuz** [comment]
See badge that's in Bohol.
