### ISSUE TITLE
No more Register link

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#59]
When clicking "Login" button, there is a link at the bottom right of the form which says "Register". 

This is not needed anymore. Only the super admin user can add new admin accounts when he is logged into the system.

No registration of users is required. Only creation of users by the super admin user once he is logged in.

Assigned to: fskreuz and chuakarlo

**Comment by fskreuz** [comment]
On it.

**Comment by fskreuz** [comment]
Done: https://github.com/fskreuz/Tree-Trail/commit/7e574fec8743e08d8d80769495e5f040341256dc
