### ISSUE TITLE
Add Badge Bug

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#63]
Newly added badge immediately reflected on the map even when not logged in as admin user.

Kindly fix this. Thanks!

**Comment by MarianneBorces** [comment]
if using the super admin account, walay mahitabo after i-click si save button.

**Comment by mitziel** [comment]
-upload function doesn't work
-there might be an alert message for the admin side but in guest side, there's no alert message....
-both in Admin and guest side, after adding a new badge, when clicking to another place, the information that was last inputted still remains...

**Comment by mitziel** [comment]
-dba if mu.add ug new badge ang Admin mismo kay it doesn't need any approval to any admin , including him/herself. Because it is to be directly reflected to the map without any approval anymore

**Comment by fskreuz** [comment]
https://github.com/fskreuz/Tree-Trail/commit/950faaab3b8e6233daf4d3c498701d99b39879a8

**Comment by MarianneBorces** [comment]
close this. RESOLVED nani na issue

**Comment by fskreuz** [comment]
All caps para intense. Hahaha
