### ISSUE TITLE
Delete Badge Bug

### ISSUE THREAD

**Issue by jeanathegreat** [fskreuz/Tree-Trail#65]
What happaned: Even when not logged in as an admin user, I was able to successfully delete an existing badge on the map.

What should have happened: I should not have been able to delete the badge. When not logged in and the user clicks on the Delete Badge button (Trash Bin icon), it should inform the user that he/she doesn't have the administrative priviliges to do so.

**Comment by MarianneBorces** [comment]
How to delete when there is no badge to delete?

**Comment by fskreuz** [comment]
Pls add badges :D

**Comment by jeanathegreat** [comment]
Current issue as of 3/15/15 4:30PM

1. Logged in as admin
2. Clicked on an unapproved badge
3. Sidebar appears
4. No delete badge option
5. Clicked on an approved badge
6. Sidebar appears
7. No delete badge option

Solution:
Kindly add Delete badge option

**Comment by fskreuz** [comment]
@jeanathegreat Removed the delete icon for unapproved badges because reject does the same thing - delete the badge.

**Comment by MarianneBorces** [comment]
using the admin account.
when you click delete icon, a pop up message stating that the badge is deleted and along with it an attention message pop up on the right side of the screen asking for an approval to add the badge. but after that it successfully deletes the badge

**Comment by fskreuz** [comment]
Fixed with https://github.com/fskreuz/Tree-Trail/commit/56dc8a96477159b9c77ed3c8edc76109ea3b1f98

**Comment by MarianneBorces** [comment]
there's a blank pop-up on the right side. its not needed
