### ISSUE TITLE
'Add A Badge' UI improvement

### ISSUE THREAD

**Issue by mitziel** [fskreuz/Tree-Trail#67]
When a badge is clicked, a sidebar form shows up. To improve the user experience, allow the user to have an option to close the sidebar form as to not give inconvenience in viewing the map when the sidebar form is not needed anymore.

**Comment by mitziel** [comment]
oops, wa ko ka klaro sa Close link, i was looking for something obvious like X button or red button for exit/close

**Comment by fskreuz** [comment]
@mitziel Cancel button nah xa ron.
