### ISSUE TITLE
Add Badge Bug

### ISSUE THREAD

**Issue by mitziel** [fskreuz/Tree-Trail#76]
When a guest finishes filling up:
-how can one know if the image was successfully uploaded?
-how can one know if the badge inputted was saved? because there's no any prompt message that the guest can see, leaving them unaware that once the Save button is clicked, it was successfully saved as pending request in the admin badge management side. Perhaps there would be a pop-up message to inform the guest that the newly added badge is still pending for approval and then the sidebar exits/hides. or something that informs the guest...

**Comment by mitziel** [comment]
there's an alert message for the admin side only, but there's none for the guest side

**Comment by mitziel** [comment]
-dba if mu.add ug new badge ang Admin mismo kay it doesn't need any approval to any admin , including him/herself. Because it is to be directly reflected to the map without any approval anymore

**Comment by mitziel** [comment]
-uplaoad image is not working
-GUEST SIDE: wlay alert message na mu.prompt after adding a new badge

**Comment by mitziel** [comment]
- if amdin adds a badge, it should be directly reflected to the map, no need for any approval...am i right?

**Comment by fskreuz** [comment]
> how can one know if the image was successfully uploaded?

The images are actually uploaded even before save. Kung mu appear na ang picture and mu revert na ang button to "Upload". All save does is reference that image.

> how can one know if the badge inputted was saved?

Notif added in this commit https://github.com/fskreuz/Tree-Trail/commit/25d02cf51cc8530beedc19685297e42481eb699d. For Admin, the badge just appears on the map.

**Comment by MarianneBorces** [comment]
okay. close this
