### ISSUE TITLE
Add a Badge Bug

### ISSUE THREAD

**Issue by mitziel** [fskreuz/Tree-Trail#80]
-upload function doesn't work
-there might be an alert message for the admin side but in guest side, there's no alert message....
-both in Admin and guest side, after adding a new badge, when clicking to another place, the information that was last inputted still remains...

**Comment by mitziel** [comment]
-dba if mu.add ug new badge ang Admin mismo kay it doesn't need any approval to any admin , including him/herself. Because it is to be directly reflected to the map without any approval anymore

**Comment by MarianneBorces** [comment]
close this. redundancy.
