### ISSUE TITLE
Badges added by the admin

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#81]
Badges added by the admin are not automatically approved. Still awaits for approval from the admin.

**Comment by MarianneBorces** [comment]
-dba if mu.add ug new badge ang Admin mismo kay it doesn't need any approval to any admin , including him/herself. Because it is to be directly reflected to the map without any approval anymore

**Comment by MarianneBorces** [comment]
-uplaoad image is not working

**Comment by orvzjhp** [comment]
Yes. Badges added by the admin should be automatically approved and reflected to the map.

**Comment by MarianneBorces** [comment]
AND if mo add nasad ka kay mo retain ang imo gi-type previously. please i-balik ang default

**Comment by jeanathegreat** [comment]
Current issue as of 03/15/15 4:30PM.

Logged in as admin.
Tried to add badge.
Badge was added.
Waiting for moderation prompt appeared. 
Colored Badge reflected on map.

Admin can add badge. But upon adding, a prompt is shown saying that the added badge is pending for approval when in fact the admin is the one who added the badge.

**Comment by jeanathegreat** [comment]
Solution:

When logged in as admin, badge added should be reflected in the map automatically without any prompt.

**Comment by fskreuz** [comment]
@jeanathegreat Clear cache or hard reload `CTRL+SHIFT+R`. That's already fixed: https://github.com/fskreuz/Tree-Trail/commit/950faaab3b8e6233daf4d3c498701d99b39879a8
