### ISSUE TITLE
Texts from the previous Badge.

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#82]
Previous information from the previous badge you added are not cleared once you add a new badge. You still have to refresh it to clear all the texts in the textbox in the add badge.

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/3a82b6204c311051e5626d0b35a1e9af8e2db293

**Comment by MarianneBorces** [comment]
when you are using admin account example "marriane" username "p@ssw0rd" password,
Step 1: add a badge
Step 2: canceled it
Step 3: add again
the mandatory fields will not return to default mode. 

ALSO same account.
Step 1: add a badge successfully
Step 2: add another badge, the abundance of tree in the area will not return to its default selected value.

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/b0145b31f0dea5c5de1bbb23693d496414bb021a
