### ISSUE TITLE
Add pending badge by Guests

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#84]
Not working.

**Comment by MarianneBorces** [comment]
there's an alert message for the admin side only, but there's none for the guest side

**Comment by orvzjhp** [comment]
Guest can't add badges. Add button not working

**Comment by MarianneBorces** [comment]
uplaoad image is not working

**Comment by fskreuz** [comment]
Fixed: https://github.com/fskreuz/Tree-Trail/commit/826ec540afa55d8f3bc5d515d4bf20e39efe3f2b
