### ISSUE TITLE
LOGOUT BUG

### ISSUE THREAD

**Issue by MarianneBorces** [fskreuz/Tree-Trail#91]
Bug where in naay problem sa logout

**Comment by orvzjhp** [comment]
Logout function is not working. Once clicked, you will still be redirected to the homepage where logout button is still present.

**Comment by fskreuz** [comment]
Fixed https://github.com/fskreuz/Tree-Trail/commit/d829259e2d646db9ed4ed3e71d212b34eda1596a

**Comment by MarianneBorces** [comment]
okay. close
