### ISSUE TITLE
Administrator Dashboard on Admin Users

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#95]
![](https://scontent-sea.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/10376274_965888340090721_5765725540978974472_n.jpg?oh=a2273503455163938b57ee52a6671f21&oe=55833354)

PHP error when clicked on Administrator Dashboard in Admin account

**Comment by fskreuz** [comment]
Screenshot?? Pwede ra printscreen, nya paste diretso diri github.

**Comment by orvzjhp** [comment]
maka post rag picture diri ?

**Comment by fskreuz** [comment]
print screen, nya ctrl+v ra diretso diri sa comments.

**Comment by orvzjhp** [comment]
dli ko ka paste man.

**Comment by fskreuz** [comment]
Press print screen. Then click sa text area diri, nya ctrl+v

**Comment by orvzjhp** [comment]
dli jd siya. i posted nlang the picture sa group.

**Comment by harriete** [comment]
pending pa ako pr :<

**Comment by fskreuz** [comment]
@harriete ok na ang imo PR. deployed na. Wala lang nako gi merge sa github, sa ako local ra nko gi merge kay naa conflicts which I can fix.

**Comment by chuakarlo** [comment]
Fixed..

**Comment by MarianneBorces** [comment]
tangtanga nalang ang dashboard na link please.

**Comment by MarianneBorces** [comment]
@chuakarlo please tangtanga ang dashboard na link. thanks!
