### ISSUE TITLE
PHP error on Super Admin Login

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#96]
When Super Admin account is logged in, it prompts a PHP error.

**Comment by orvzjhp** [comment]
PHP error on Tree Trail button from the Nav Bar.

**Comment by fskreuz** [comment]
Screnshot? Logs? I don't have a crystal ball.

**Comment by orvzjhp** [comment]
screenshot added on FB goup, for some reason, dli ko ka paste sa screenshots the way u asked me to.

**Comment by chuakarlo** [comment]
Fixed. Please test to confirm

**Comment by alkevinc** [comment]
Fixed.
