### ISSUE TITLE
Edit approve and unapproved badge/s

### ISSUE THREAD

**Issue by MarianneBorces** [fskreuz/Tree-Trail#98]
An admin user can have the option to edit any type of badge whether it is approved or unapproved.

**Comment by fskreuz** [comment]
https://github.com/fskreuz/Tree-Trail/commit/41a59c13b2503f60cf75bef9b3f06a607c4e37d2

**Comment by MarianneBorces** [comment]
Issue: if unapprove badge, nya i-edit then save it, it will immediately approve the badge.

expected output: it should not approve or reject. it should remain unapproved
